"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.seedAnglaisLessons = seedAnglaisLessons;
var db_1 = require("@workspace/db");
var drizzle_orm_1 = require("drizzle-orm");
var logger_1 = require("./logger");
var ANGLAIS_SUBJECT_ID = 7;
var SEED_MARKER_ORDER_START = 5;
var anglaisLessons = [
    {
        title: "Leçon 1 : Talking about past habits",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 5,
        duration: 45,
        isPremium: false,
        summary: "Learn how to describe past habits and repeated actions using used to, would, and the simple past tense.",
        keyPoints: "\"Used to + infinitive\" expresses past habits AND past states that no longer exist\n\"Would + infinitive\" expresses ONLY repeated past actions (not states)\nSimple past + frequency adverb also expresses past habits\nNegative of \"used to\": did not use to (NOT \"didn't used to\")\n\"Would\" cannot replace \"used to\" for states (feelings, situations)",
        content: "<h2>Talking About Past Habits</h2>\n<p>In English, we use specific structures to talk about things we did regularly or habitually in the past but no longer do today. The three main ways are: <strong>used to + infinitive</strong>, <strong>would + infinitive</strong>, and the <strong>simple past</strong>.</p>\n<h3>1. Used to + Infinitive</h3>\n<p><em>Used to</em> expresses a past habit or a past state that no longer exists. It is used for both actions and states.</p>\n<ul>\n  <li><strong>Form:</strong> Subject + used to + base verb</li>\n  <li><strong>Negative:</strong> Subject + did not (didn't) use to + base verb</li>\n  <li><strong>Question:</strong> Did + subject + use to + base verb?</li>\n</ul>\n<p>Examples: She <em>used to walk</em> to school every day. They <em>used to live</em> in a small village. He <em>didn't use to like</em> vegetables.</p>\n<h3>2. Would + Infinitive</h3>\n<p><em>Would</em> can also express past habits, but it is only used for <strong>repeated actions</strong> \u2014 NOT for past states.</p>\n<ul>\n  <li>Every evening, my grandfather <em>would sit</em> by the fire and tell us stories.</li>\n  <li>\u274C She would be tall. (WRONG \u2014 use \"used to be\")</li>\n</ul>\n<h3>3. The Simple Past for Past Habits</h3>\n<p>The simple past with adverbs like <em>always, often, sometimes, never, every day</em> also describes past habits.</p>\n<ul><li>As a child, I <em>always played</em> outside after school.</li></ul>\n<h3>Key Differences</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Structure</th><th>Past actions</th><th>Past states</th></tr>\n  <tr><td>used to</td><td>\u2705 Yes</td><td>\u2705 Yes</td></tr>\n  <tr><td>would</td><td>\u2705 Yes</td><td>\u274C No</td></tr>\n  <tr><td>Simple past + adverb</td><td>\u2705 Yes</td><td>\u2705 Yes</td></tr>\n</table>",
        examples: "<p><strong>Example 1 \u2013 Used to (habit):</strong> My father <em>used to work</em> as a teacher before he retired. He <em>used to wake up</em> very early every morning.</p>\n<p><strong>Example 2 \u2013 Used to (state):</strong> There <em>used to be</em> a big mango tree in our compound. I <em>used to be</em> afraid of the dark.</p>\n<p><strong>Example 3 \u2013 Would (repeated action):</strong> Every evening, we <em>would run</em> to the market and <em>would buy</em> mangoes and groundnuts.</p>\n<p><strong>Example 4 \u2013 Comparison:</strong><br>\u274C He would live in Abidjan. (state \u2014 wrong!)<br>\u2705 He used to live in Abidjan.</p>\n<p><strong>Example 5 \u2013 Simple past + adverb:</strong> She <em>always brought</em> food for her classmates. They <em>sometimes stayed</em> late at school to study.</p>",
    },
    {
        title: "Leçon 2 : Expressing possibility, ability, obligation and necessity",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 6,
        duration: 50,
        isPremium: false,
        summary: "Master modal verbs to express possibility, ability, obligation, necessity, prohibition and advice in English.",
        keyPoints: "\"Can\" expresses present ability; \"could\" expresses past ability\n\"May\" expresses higher possibility (50%); \"might\" expresses lower possibility (30%)\n\"Must\" expresses internal/personal obligation; \"have to\" expresses external rules\n\"Should / ought to\" expresses advice or recommendations\n\"Must not\" = prohibition (forbidden); \"don't have to\" = no obligation (a choice)\nModal verbs are always followed by a bare infinitive (base form)",
        content: "<h2>Modal Verbs: Possibility, Ability, Obligation and Necessity</h2>\n<p>Modal verbs are auxiliary verbs used to express degrees of certainty, ability, obligation, and necessity.</p>\n<h3>1. Expressing Ability</h3>\n<p><strong>Can</strong> (present) and <strong>could</strong> (past) express ability.</p>\n<ul>\n  <li>She <em>can speak</em> three languages. (present ability)</li>\n  <li>When I was young, I <em>could swim</em> very well. (past ability)</li>\n</ul>\n<h3>2. Expressing Possibility</h3>\n<p><strong>May</strong> (more certain ~50%) and <strong>might</strong> (less certain ~30%) express possibility.</p>\n<ul>\n  <li>It <em>may rain</em> tonight. / She <em>might come</em> to the party.</li>\n</ul>\n<h3>3. Expressing Obligation and Necessity</h3>\n<p><strong>Must</strong> (internal obligation) vs <strong>have to</strong> (external rule):</p>\n<ul>\n  <li>I <em>must study</em> harder. (personal decision)</li>\n  <li>Students <em>have to wear</em> uniforms. (school rule)</li>\n</ul>\n<h3>4. Expressing Advice</h3>\n<p><strong>Should</strong> and <strong>ought to</strong> give advice:</p>\n<ul><li>You <em>should eat</em> more vegetables. / She <em>ought to apologise</em>.</li></ul>\n<h3>5. Prohibition vs No Obligation</h3>\n<ul>\n  <li><strong>Must not</strong> = forbidden: You <em>must not smoke</em> here.</li>\n  <li><strong>Don't have to</strong> = optional: You <em>don't have to come</em>.</li>\n</ul>\n<h3>Summary Table</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Modal</th><th>Use</th></tr>\n  <tr><td>can / could</td><td>Ability</td></tr>\n  <tr><td>may / might</td><td>Possibility</td></tr>\n  <tr><td>must</td><td>Strong obligation (internal)</td></tr>\n  <tr><td>have to</td><td>Obligation (external rule)</td></tr>\n  <tr><td>should / ought to</td><td>Advice</td></tr>\n  <tr><td>must not</td><td>Prohibition</td></tr>\n  <tr><td>don't have to</td><td>No obligation</td></tr>\n</table>",
        examples: "<p><strong>Ability:</strong> Kofi <em>can play</em> the guitar beautifully. When he was a child, he <em>could not read</em> music.</p>\n<p><strong>Possibility:</strong> The results <em>may be</em> announced tomorrow. They <em>might be</em> delayed. There <em>could be</em> a problem.</p>\n<p><strong>Obligation:</strong> All candidates <em>must bring</em> their ID card. Students <em>have to arrive</em> before 8 a.m.</p>\n<p><strong>Advice:</strong> You look tired. You <em>should take</em> a break. You <em>ought to drink</em> more water.</p>\n<p><strong>No obligation vs Prohibition:</strong><br>\nYou <em>don't have to wear</em> a tie \u2014 it is optional.<br>\nYou <em>must not bring</em> your phone into the exam room \u2014 it is strictly forbidden.</p>",
    },
    {
        title: "Leçon 3 : The past simple and the past perfect simple + Indefinite relative pronouns",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 7,
        duration: 55,
        isPremium: false,
        summary: "Compare the past simple and past perfect simple for sequencing events, and master indefinite relative pronouns (whoever, whatever, wherever...).",
        keyPoints: "Past simple = completed action at a specific past time (verb + -ed or irregular form)\nPast perfect = action completed BEFORE another past action (had + past participle)\nPast perfect signals: already, just, never, after, before, by the time\nTwo past events: past perfect for the EARLIER one, past simple for the LATER one\nWhoever = any person / Whatever = any thing / Wherever = any place\nWhenever = any time / Whichever = any choice / However = in any way",
        content: "<h2>Part A: The Past Simple and the Past Perfect Simple</h2>\n<h3>1. The Past Simple</h3>\n<p>The <strong>past simple</strong> is used for completed actions that happened at a specific time in the past.</p>\n<ul>\n  <li><strong>Regular verbs:</strong> verb + -ed \u2192 walked, studied, arrived</li>\n  <li><strong>Irregular verbs:</strong> go \u2192 went, see \u2192 saw, write \u2192 wrote</li>\n</ul>\n<h3>2. The Past Perfect Simple</h3>\n<p>The <strong>past perfect</strong> describes an action <strong>completed BEFORE another past action</strong>. Form: <em>had + past participle</em>.</p>\n<ul>\n  <li>Key signals: <em>after, before, when, already, just, never, by the time</em></li>\n</ul>\n<h3>3. Using Both Tenses Together</h3>\n<p>Past perfect = earlier action \u2192 Past simple = more recent action</p>\n<ul><li>When I <em>arrived</em>, the train <em>had already left</em>.</li></ul>\n<h2>Part B: Indefinite Relative Pronouns</h2>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Pronoun</th><th>Meaning</th><th>Example</th></tr>\n  <tr><td>whoever</td><td>any person who</td><td>Whoever arrives first wins.</td></tr>\n  <tr><td>whatever</td><td>anything that</td><td>Do whatever you think is right.</td></tr>\n  <tr><td>whichever</td><td>any one of a group</td><td>Choose whichever you prefer.</td></tr>\n  <tr><td>wherever</td><td>any place where</td><td>Sit wherever you like.</td></tr>\n  <tr><td>whenever</td><td>any time when</td><td>Call me whenever you need help.</td></tr>\n  <tr><td>however</td><td>in any way</td><td>Do it however you like.</td></tr>\n</table>",
        examples: "<p><strong>Past Perfect vs Past Simple (1):</strong><br>\nWhen I <em>arrived</em> at the station, the train <em>had already left</em>.<br>\n\u2192 First: the train left. Then: I arrived.</p>\n<p><strong>(2):</strong> She <em>had studied</em> all night before she <em>sat</em> the exam.</p>\n<p><strong>(3 \u2013 narrative):</strong> After he <em>had eaten</em>, he <em>washed</em> the dishes and <em>went</em> to bed.</p>\n<p><strong>Indefinite relative pronouns:</strong><br>\n<em>Whoever</em> finishes first can help the others.<br>\nI will support you <em>whatever</em> decision you make.<br>\nThey followed him <em>wherever</em> he went.<br>\nYou may borrow <em>whichever</em> book interests you most.<br>\nCome and visit us <em>whenever</em> you are in town.<br>\n<em>However</em> difficult the exam is, do not give up.</p>",
    },
    {
        title: "Leçon 4 : Past form of modal verbs",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 8,
        duration: 55,
        isPremium: false,
        summary: "Learn to use past modal forms (must have, could have, should have, might have...) to express certainty, regret, criticism and possibility about past situations.",
        keyPoints: "Past modals = modal + have + past participle\n\"Must have\" = strong certainty about the past (almost sure it happened)\n\"Can't have / couldn't have\" = certainty that something did NOT happen\n\"May have / might have\" = past possibility (not sure)\n\"Should have\" = regret or criticism (right thing not done)\n\"Shouldn't have\" = past mistake (wrong thing that was done)\n\"Could have\" = past possibility/ability that was not used\n\"Would have\" = hypothetical past (used in the third conditional)",
        content: "<h2>Past Form of Modal Verbs</h2>\n<p>Past modals are formed with a modal verb + <strong>have + past participle</strong>. They express speculation, regret, or criticism about past situations.</p>\n<h3>1. Must have + p.p. \u2014 Certainty</h3>\n<p>Almost certain something happened: She <em>must have forgotten</em> her keys. You walked 10 km! You <em>must have been</em> exhausted.</p>\n<h3>2. Can't have / Couldn't have + p.p. \u2014 Impossibility</h3>\n<p>Almost certain it did NOT happen: He <em>can't have passed</em> \u2014 he never studied!</p>\n<h3>3. May have / Might have + p.p. \u2014 Past possibility</h3>\n<p>Possible but uncertain: They <em>may have missed</em> the bus. She <em>might have gone</em> home.</p>\n<h3>4. Should have + p.p. \u2014 Regret / Criticism</h3>\n<p>Right thing not done: You <em>should have studied</em> more. I <em>ought to have apologised</em> earlier.</p>\n<h3>5. Shouldn't have + p.p. \u2014 Past mistake</h3>\n<p>Wrong thing that was done: She <em>shouldn't have said</em> that.</p>\n<h3>6. Could have + p.p. \u2014 Missed opportunity</h3>\n<p>Possible but not used: I <em>could have won</em>, but I fell.</p>\n<h3>7. Would have + p.p. \u2014 Hypothetical past</h3>\n<p>Third conditional: If I had known, I <em>would have helped</em> you.</p>\n<h3>Summary Table</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Structure</th><th>Meaning</th></tr>\n  <tr><td>must have + p.p.</td><td>Almost certain it happened</td></tr>\n  <tr><td>can't/couldn't have + p.p.</td><td>Almost certain it did NOT happen</td></tr>\n  <tr><td>may/might have + p.p.</td><td>Possible, not sure</td></tr>\n  <tr><td>should have + p.p.</td><td>Regret \u2014 right thing not done</td></tr>\n  <tr><td>shouldn't have + p.p.</td><td>Mistake \u2014 wrong thing done</td></tr>\n  <tr><td>could have + p.p.</td><td>Missed opportunity</td></tr>\n  <tr><td>would have + p.p.</td><td>Hypothetical/unrealised past</td></tr>\n</table>",
        examples: "<p><strong>Certainty:</strong> The lights are off and her car is gone. She <em>must have left</em> already.</p>\n<p><strong>Impossibility:</strong> He <em>can't have cheated</em>. The teacher was watching the whole time.</p>\n<p><strong>Possibility:</strong> I don't see my pen. I <em>might have left</em> it at school, or I <em>may have dropped</em> it.</p>\n<p><strong>Regret / Criticism:</strong> The accident was serious. You <em>should have driven</em> more carefully. I <em>should have warned</em> you earlier.</p>\n<p><strong>Past mistake:</strong> You <em>shouldn't have told</em> him the secret. Now everyone knows!</p>\n<p><strong>Missed opportunity:</strong> We arrived 10 minutes late. We <em>could have taken</em> a taxi instead of walking.</p>\n<p><strong>Hypothetical past:</strong> If they had trained harder, they <em>would have won</em> the championship.</p>",
    },
    {
        title: "Leçon 5 : A letter of complaint",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 9,
        duration: 50,
        isPremium: false,
        summary: "Learn how to write a formal letter of complaint: structure, formal language, useful phrases, and how to request a solution effectively.",
        keyPoints: "A letter of complaint is formal: no contractions, polite but firm tone\nLayout: your address \u2192 date \u2192 recipient address \u2192 subject line \u2192 salutation\nPara 1: Introduction and context (who you are, what you bought, when)\nPara 2: Describe the problem clearly with facts and dates\nPara 3: Explain the consequences/impact on you\nPara 4: State the action expected and a deadline\nUse \"Yours faithfully\" when salutation is \"Dear Sir/Madam\"\nUse \"Yours sincerely\" when you addressed the person by name",
        content: "<h2>How to Write a Letter of Complaint</h2>\n<p>A letter of complaint is a <strong>formal letter</strong> written to express dissatisfaction and request a solution. It must be polite but firm, factual, and well-structured.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Formal tone: polite but firm</li>\n  <li>No contractions (I am NOT I'm)</li>\n  <li>Clear, factual language</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Your address</strong> (top right) \u2192 <strong>Date</strong> \u2192 <strong>Recipient's address</strong> (left)<br>\n<strong>Subject:</strong> RE: Complaint about [issue]<br>\n<strong>Salutation:</strong> Dear Sir/Madam (unknown) / Dear Mr/Mrs [Name] (known)<br>\n<strong>Para 1:</strong> Purpose + background (where/when purchased, reference number)<br>\n<strong>Para 2:</strong> Describe the problem with specific facts and dates<br>\n<strong>Para 3:</strong> Consequences/impact on you<br>\n<strong>Para 4:</strong> Action expected + deadline<br>\n<strong>Closing:</strong> I look forward to hearing from you.<br>\n<strong>Sign-off:</strong> Yours faithfully / Yours sincerely<br>\n<strong>Full name (printed)</strong></p>\n<h3>3. Useful Expressions</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Useful phrases</th></tr>\n  <tr><td>Purpose</td><td>I am writing to complain about... / I am writing with regard to...</td></tr>\n  <tr><td>Problem</td><td>I was disappointed to find that... / Unfortunately, the product was...</td></tr>\n  <tr><td>Request</td><td>I would be grateful if you could... / I request that you...</td></tr>\n  <tr><td>Deadline</td><td>I would appreciate a response within 14 days.</td></tr>\n</table>",
        examples: "<p><strong>Model letter:</strong></p>\n<p>12, Rue des Fleurs, Abidjan, Cocody<br>9th April 2026</p>\n<p>The Customer Service Manager<br>TeleConnect Mobile Services, Abidjan</p>\n<p><strong>RE: Complaint about defective mobile phone</strong></p>\n<p>Dear Sir/Madam,</p>\n<p>I am writing to complain about a mobile phone (Model: Samsung Galaxy A15, Ref. TC-20456) purchased on 25th March 2026 for 85,000 CFA francs.</p>\n<p>Unfortunately, after five days of use, the screen developed a serious fault: it displays a black line and frequently freezes. Despite following the user manual, the problem has persisted.</p>\n<p>As a result, I have been unable to use the device for my studies, causing considerable inconvenience.</p>\n<p>I would therefore be grateful if you could replace the phone or issue a full refund by 30th April 2026. I enclose a copy of my receipt as proof of purchase.</p>\n<p>I look forward to hearing from you.</p>\n<p>Yours faithfully,<br><strong>Kouam\u00E9 Adama</strong></p>",
    },
    {
        title: "Leçon 6 : An informal email",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 10,
        duration: 45,
        isPremium: false,
        summary: "Master the structure and language of informal emails: greetings, friendly expressions, sharing news, and appropriate sign-offs for friends and family.",
        keyPoints: "Informal emails are written to friends or family \u2014 use a warm, friendly tone\nContractions are acceptable: I'm, you're, don't, it's, can't\nOpening: greet the person and re-establish contact (How are you? Long time no see!)\nBody: share news, answer questions, use linking words (anyway, by the way, guess what!)\nClosing: wrap up naturally and invite a reply (Write back soon! / Can't wait to hear from you!)\nSign-off: Love / Take care / Best wishes / Cheers + first name only\nNo formal address or subject line required in informal emails",
        content: "<h2>How to Write an Informal Email</h2>\n<p>An <strong>informal email</strong> is written to a friend or family member. The language is friendly, relaxed, and personal.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Friendly and warm tone</li>\n  <li>Contractions are allowed: I'm, you're, it's, don't, can't</li>\n  <li>Colloquial expressions are acceptable</li>\n  <li>Personal questions and comments</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Subject:</strong> Short and catchy (e.g., \"Great news!\" / \"Missing you!\")<br>\n<strong>Greeting:</strong> Hi [Name]! / Hello [Name]! / Hey [Name]!<br>\n<strong>Opening:</strong> Re-establish contact \u2014 How are you? / It's been ages!<br>\n<strong>Body:</strong> Share news, answer questions, use: anyway, by the way, guess what!<br>\n<strong>Closing:</strong> Write back soon! / Can't wait to hear from you!<br>\n<strong>Sign-off:</strong> Love, / Take care, / Best wishes, / Cheers,<br>\n<strong>First name only</strong></p>\n<h3>3. Useful Language</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Opening</td><td>Hope you're well! / How have you been? / Long time no see!</td></tr>\n  <tr><td>Sharing news</td><td>Guess what! / You won't believe it! / I've got exciting news!</td></tr>\n  <tr><td>Asking for news</td><td>How are things? / What have you been up to? / How's school?</td></tr>\n  <tr><td>Closing</td><td>Write back soon! / Keep in touch! / Can't wait to see you!</td></tr>\n</table>\n<h3>4. Formal vs Informal</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Formal</th><th>Informal</th></tr>\n  <tr><td>Dear Sir/Madam</td><td>Hi Kofi! / Hey Ama!</td></tr>\n  <tr><td>I am writing to inform you</td><td>I just wanted to tell you</td></tr>\n  <tr><td>Yours faithfully/sincerely</td><td>Love / Take care / Cheers</td></tr>\n</table>",
        examples: "<p><strong>Subject:</strong> Exciting news from Abidjan!</p>\n<p>Hi Fatou!</p>\n<p>How are you? I hope everything is going well. It's been such a long time since we last chatted \u2014 I've been meaning to write for weeks!</p>\n<p>Anyway, I have some really exciting news. Guess what? I finally passed my pre-bac mock exams and got the highest score in my class! I'm so relieved and happy. All those late nights really paid off. My mum was so proud \u2014 she even made my favourite dish to celebrate!</p>\n<p>By the way, I heard you're coming to Abidjan next month for the holidays. Is that true? I really hope so! We could visit the beach and catch up properly.</p>\n<p>What have you been up to lately? How's school going? Drop me a message when you can \u2014 I can't wait to hear all your news!</p>\n<p>Write back soon!</p>\n<p>Lots of love,<br><strong>Aminata</strong></p>",
    },
    // ── Unité 3 ────────────────────────────────────────────────────────────────
    {
        title: "Leçon 1 (Unité 3) : Language function – Making causative sentences & Making comparisons",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 11,
        duration: 50,
        isPremium: false,
        summary: "Learn to form causative sentences using make, let, have, get and help, and make comparisons using comparative and superlative structures.",
        keyPoints: "Causative verbs arrange for others to do things: make / let / have / get / help\n\"Make\" and \"let\" take object + bare infinitive (no \"to\")\n\"Get\" takes object + to-infinitive\n\"Have\" takes object + bare infinitive (professional services)\nComparative of short adjectives: add -er + than\nComparative of long adjectives: more + adjective + than\nSuperlative: the + -est (short) / the most + adjective (long)\nEquality: as + adjective/adverb + as / Inequality: not as ... as\nMore/fewer with countable nouns; more/less with uncountable nouns",
        content: "<h2>Part A: Making Causative Sentences</h2>\n<p>A <strong>causative sentence</strong> expresses that someone arranges for another person to do something on their behalf.</p>\n<h3>Causative Verbs</h3>\n<ul>\n  <li><strong>Make</strong> \u2013 force: <em>make + object + bare infinitive</em> \u2192 The teacher <em>made the students rewrite</em> their essays.</li>\n  <li><strong>Let</strong> \u2013 allow: <em>let + object + bare infinitive</em> \u2192 Her parents <em>let her stay</em> out late.</li>\n  <li><strong>Have</strong> \u2013 arrange (service): <em>have + object + bare infinitive</em> \u2192 She <em>had the mechanic check</em> her car.</li>\n  <li><strong>Get</strong> \u2013 persuade: <em>get + object + to-infinitive</em> \u2192 He <em>got his brother to fix</em> his computer.</li>\n  <li><strong>Help</strong> \u2013 assist: <em>help + object + bare/to-infinitive</em> \u2192 She <em>helped me carry</em> the boxes.</li>\n</ul>\n<h2>Part B: Making Comparisons</h2>\n<h3>1. Comparative of Adjectives</h3>\n<ul>\n  <li>Short adjectives: add <strong>-er \u2026 than</strong> \u2192 taller than, faster than</li>\n  <li>Long adjectives: <strong>more \u2026 than</strong> \u2192 more intelligent than</li>\n  <li>Irregular: good \u2192 better / bad \u2192 worse / far \u2192 farther/further</li>\n</ul>\n<h3>2. Superlative</h3>\n<ul>\n  <li>Short: add <strong>-est</strong> \u2192 the tallest / Long: <strong>the most</strong> \u2192 the most intelligent</li>\n  <li>Irregular: good \u2192 the best / bad \u2192 the worst</li>\n</ul>\n<h3>3. Equality and Inequality</h3>\n<ul>\n  <li>Equality: <strong>as + adjective + as</strong> \u2192 She is as tall as her sister.</li>\n  <li>Inequality: <strong>not as \u2026 as</strong> \u2192 This is not as interesting as the other.</li>\n</ul>\n<h3>4. Quantities</h3>\n<ul>\n  <li><strong>more / fewer / less \u2026 than</strong> \u2192 He has more books than I do. There are fewer students than last year.</li>\n</ul>",
        examples: "<p><strong>Causative sentences:</strong><br>\nThe boss <em>made everyone work</em> overtime last Friday.<br>\nThe coach <em>let the players rest</em> after training.<br>\nShe <em>had a tailor make</em> her dress for the ceremony.<br>\nI <em>got my friend to proofread</em> my application letter.</p>\n<p><strong>Comparisons:</strong><br>\nKofi is <em>taller than</em> his classmate, but not <em>as fast as</em> him.<br>\nThis exercise is <em>more difficult than</em> the previous one.<br>\nShe is <em>the most hardworking student</em> in the class.<br>\nWe have <em>fewer resources</em> but <em>more determination</em> than anyone else.</p>",
    },
    {
        title: 'Leçon 2 (Unité 3) : Language corner – Causative structures with "have" and "get"',
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 12,
        duration: 50,
        isPremium: false,
        summary: 'Master the causative structures "have/get something done" to talk about arranged services and experiences using past participles.',
        keyPoints: "\"Have something done\" = subject arranges for someone else to do it (professional service)\nStructure: have + object + past participle\n\"Get something done\" = similar to \"have\" but slightly informal or implies effort\nStructure: get + object + past participle\n\"Have someone do\" = have + person + bare infinitive\n\"Get someone to do\" = get + person + to-infinitive\nExperiential causative: have/get + object + past participle = unpleasant thing that happened to subject\nChange the tense of \"have/get\" to place the action in time (past, future, perfect, etc.)",
        content: "<h2>Causative Structures with \"Have\" and \"Get\"</h2>\n<h3>1. Have something done (arranged service)</h3>\n<p><strong>Structure:</strong> Subject + <em>have</em> + object + <strong>past participle</strong></p>\n<ul>\n  <li>She <em>had her hair cut</em> at the salon.</li>\n  <li>They <em>had their house painted</em> last summer.</li>\n</ul>\n<h3>2. Get something done (informal)</h3>\n<p><strong>Structure:</strong> Subject + <em>get</em> + object + <strong>past participle</strong></p>\n<ul>\n  <li>I must <em>get my passport renewed</em> before the trip.</li>\n  <li>She finally <em>got her laptop fixed</em>.</li>\n</ul>\n<h3>3. Naming the agent</h3>\n<ul>\n  <li><em>Have + person + bare infinitive:</em> She <em>had the plumber fix</em> the pipes.</li>\n  <li><em>Get + person + to-infinitive:</em> She <em>got the plumber to fix</em> the pipes.</li>\n</ul>\n<h3>4. Experiential Causative (Unpleasant events)</h3>\n<p>The same structure describes something unpleasant that happened TO the subject:</p>\n<ul>\n  <li>He <em>had his wallet stolen</em> on the bus. (he didn't arrange this)</li>\n  <li>They <em>got their house flooded</em> during the storm.</li>\n</ul>\n<h3>5. Tense Changes</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Tense</th><th>Example</th></tr>\n  <tr><td>Present simple</td><td>She has her nails done every week.</td></tr>\n  <tr><td>Past simple</td><td>He had his car serviced last month.</td></tr>\n  <tr><td>Future with will</td><td>I will have my teeth checked tomorrow.</td></tr>\n  <tr><td>Present perfect</td><td>They have had their roof repaired.</td></tr>\n</table>",
        examples: "<p><strong>Arranged service:</strong><br>\nAminata <em>had her dress made</em> by a talented seamstress for the graduation ceremony.<br>\nI finally <em>got my bicycle fixed</em> after it broke down for the third time.</p>\n<p><strong>Naming the agent:</strong><br>\nShe <em>had the doctor examine</em> her shoulder after the fall.<br>\nHe <em>got his classmate to explain</em> the maths problem to him.</p>\n<p><strong>Experiential causative:</strong><br>\nThe student <em>had his assignment deleted</em> when the computer crashed.<br>\nThey <em>got their shop broken into</em> last night.</p>\n<p><strong>Different tenses:</strong><br>\nShe <em>has her blood pressure checked</em> every month.<br>\nThey <em>will have their offices renovated</em> next year.</p>",
    },
    {
        title: "Leçon 3 (Unité 3) : Writing skills – A newspaper article",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 13,
        duration: 50,
        isPremium: false,
        summary: "Learn to write a well-structured newspaper article using formal language, the five Ws, headlines, quotations, and a clear lead paragraph.",
        keyPoints: "Newspaper articles answer: Who, What, When, Where, Why (and How)\nWritten in third person; formal/semi-formal tone; no contractions\nHeadline: short, present tense, eye-catching and informative\nLead paragraph: summarises the whole story in 2-3 sentences\nBody: develops the story with details, quotes, and context\nQuotes add credibility: \"According to...\", \"[Name] stated that...\"\nConclusion: outcome or future developments\nLinking words: Furthermore / Moreover / As a result / Subsequently",
        content: "<h2>How to Write a Newspaper Article</h2>\n<p>A <strong>newspaper article</strong> reports on a news event. It answers the five \"W\" questions: <strong>Who, What, When, Where, Why</strong> (and sometimes <strong>How</strong>).</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Written in the <strong>third person</strong> (he, she, they)</li>\n  <li><strong>Past simple</strong> or <strong>present perfect</strong> for reported events</li>\n  <li>Formal/semi-formal language \u2014 no slang or contractions</li>\n  <li>Quotations from witnesses or experts add credibility</li>\n  <li>Objective and factual tone</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Headline:</strong> Short, present tense, eye-catching \u2192 \"School Student Wins National Science Prize\"<br>\n<strong>By-line:</strong> Journalist's name and date<br>\n<strong>Lead paragraph:</strong> Answers Who, What, When, Where, Why in 2\u20133 sentences<br>\n<strong>Body:</strong> Details, background, context, quotes<br>\n<strong>Conclusion:</strong> Outcome or future developments</p>\n<h3>3. Language Features</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Useful language</th></tr>\n  <tr><td>Reporting</td><td>It is claimed that\u2026 / Sources confirm\u2026 / has been reported</td></tr>\n  <tr><td>Quoting</td><td>According to\u2026 / [Name] stated that\u2026 / In the words of\u2026</td></tr>\n  <tr><td>Adding details</td><td>Furthermore, / Moreover, / In addition, / As a result,</td></tr>\n</table>",
        examples: "<p><strong>Headline:</strong> Fire Destroys Market in Bouak\u00E9; Hundreds Affected</p>\n<p><strong>By-line:</strong> By Fatou Bamba | Staff Reporter | 9 April 2026</p>\n<p><strong>Lead paragraph:</strong><br>\nA devastating fire broke out in the Grand March\u00E9 of Bouak\u00E9 on Tuesday night, destroying over 200 market stalls. The blaze began at approximately 11 p.m. and was brought under control by firefighters early the following morning.</p>\n<p><strong>Body paragraph 1:</strong><br>\nAccording to eyewitnesses, the fire started in the fabric section before spreading rapidly due to strong winds. \"I heard a loud explosion and within minutes, everything was in flames,\" said Mamadou Traor\u00E9, a nearby resident.</p>\n<p><strong>Body paragraph 2:</strong><br>\nThe cause of the fire has not yet been officially confirmed. The Regional Governor visited the site on Wednesday and promised emergency assistance. Moreover, a relief fund has been set up to help traders rebuild.</p>\n<p><strong>Conclusion:</strong><br>\nThe full extent of the damage is still being assessed. Authorities have urged traders not to return until a full safety inspection is completed.</p>",
    },
    // ── Unité 4 ────────────────────────────────────────────────────────────────
    {
        title: "Leçon 4 (Unité 4) : Language function – Expressing future actions & Expressing subjective judgments and general statements",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 14,
        duration: 55,
        isPremium: false,
        summary: "Master the different ways to express future actions (will, going to, present continuous, future perfect) and learn to distinguish subjective judgments from general statements.",
        keyPoints: "\"Will\" = predictions, spontaneous decisions, promises and offers\n\"Be going to\" = planned intentions or predictions with visible evidence\nPresent continuous for future = fixed arrangements (meetings, travel)\nPresent simple for future = timetabled/scheduled events\nFuture continuous = action in progress at a specific future time (will be + -ing)\nFuture perfect = action completed before a future point (will have + past participle)\nSubjective judgments = personal opinion: I think / I believe / In my opinion / It seems\nGeneral statements = universal truths: It is said that / Studies show / Generally speaking",
        content: "<h2>Part A: Expressing Future Actions</h2>\n<h3>1. Will + bare infinitive</h3>\n<p>Predictions, spontaneous decisions, promises and offers.</p>\n<ul>\n  <li>It <em>will be</em> cold tomorrow. / I<em>'ll help</em> you! (spontaneous)</li>\n</ul>\n<h3>2. Be going to + bare infinitive</h3>\n<p>Planned intentions and evidence-based predictions.</p>\n<ul>\n  <li>She <em>is going to study</em> medicine. / Look at those clouds \u2014 it <em>is going to rain</em>.</li>\n</ul>\n<h3>3. Present Continuous for Future</h3>\n<p>Fixed arrangements with time/place.</p>\n<ul><li>We <em>are meeting</em> the director at 10 a.m. tomorrow.</li></ul>\n<h3>4. Present Simple for Future</h3>\n<p>Timetabled/scheduled events.</p>\n<ul><li>The exam <em>starts</em> at 8 a.m. on Thursday.</li></ul>\n<h3>5. Future Continuous (will be + -ing)</h3>\n<p>Action in progress at a future time.</p>\n<ul><li>At this time tomorrow, I <em>will be sitting</em> the Baccalaureate exam.</li></ul>\n<h3>6. Future Perfect (will have + past participle)</h3>\n<p>Action completed before a future time.</p>\n<ul><li>By next June, she <em>will have finished</em> her studies.</li></ul>\n<h2>Part B: Subjective Judgments and General Statements</h2>\n<h3>Subjective Judgments (personal opinions)</h3>\n<ul>\n  <li><strong>I think / I believe / I feel / In my opinion\u2026</strong></li>\n  <li>It + linking verb: <em>It seems that\u2026 / It appears that\u2026</em></li>\n</ul>\n<h3>General Statements (universal truths)</h3>\n<ul>\n  <li><strong>It is said that\u2026 / It is known that\u2026 / It is believed that\u2026</strong></li>\n  <li>Adverbs: <em>generally, usually, often, typically</em></li>\n  <li>Scientists claim that\u2026 / Studies show that\u2026</li>\n</ul>",
        examples: "<p><strong>Will:</strong> \"I'll call you as soon as I arrive,\" she promised.</p>\n<p><strong>Going to:</strong> The government <em>is going to build</em> a new hospital. Watch out! That car <em>is going to hit</em> the wall!</p>\n<p><strong>Present continuous:</strong> They <em>are presenting</em> their project to the board next Thursday.</p>\n<p><strong>Future perfect:</strong> By the time you arrive, I <em>will have prepared</em> everything.</p>\n<p><strong>Subjective judgment:</strong> In my opinion, students <em>should have access</em> to better study materials. I <em>feel that</em> the system could be improved.</p>\n<p><strong>General statement:</strong> It <em>is widely believed that</em> regular reading improves academic performance. Studies <em>show that</em> exercise boosts concentration.</p>",
    },
    {
        title: "Leçon 5 (Unité 4) : Language corner – Verb patterns with the infinitive or the gerund",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 15,
        duration: 55,
        isPremium: false,
        summary: "Learn which verbs take the to-infinitive, which take the gerund, and which take both with a change in meaning (remember, forget, stop, try).",
        keyPoints: "To-infinitive verbs: want, decide, hope, agree, refuse, manage, expect, plan, afford, choose\nGerund (-ing) verbs: enjoy, avoid, finish, suggest, mind, admit, deny, risk, keep, miss, practise\n\"Remember/forget + to-inf\" = obligation/future duty; \"+ gerund\" = past memory\n\"Stop + to-inf\" = stop in order to do; \"+ gerund\" = stop an activity\n\"Try + to-inf\" = attempt; \"+ gerund\" = experiment with something\nVerb + object + to-inf: tell, ask, advise, want, force, encourage, remind",
        content: "<h2>Verb Patterns with the Infinitive or the Gerund</h2>\n<h3>1. Verbs + TO-INFINITIVE</h3>\n<p><em>want, decide, plan, hope, agree, refuse, promise, expect, manage, afford, fail, tend, offer, need, learn, choose, seem, appear, pretend, claim</em></p>\n<ul>\n  <li>She <em>decided to leave</em> early. / He <em>refused to answer</em>. / They <em>managed to finish</em> on time.</li>\n</ul>\n<h3>2. Verbs + GERUND (-ing)</h3>\n<p><em>enjoy, avoid, finish, suggest, mind, consider, keep, admit, deny, risk, imagine, practise, miss, give up, look forward to, be used to</em></p>\n<ul>\n  <li>I <em>enjoy reading</em> English novels. / She <em>avoids making</em> mistakes. / He <em>denied stealing</em> the money.</li>\n</ul>\n<h3>3. Verbs + EITHER (change of meaning)</h3>\n<h4>Remember</h4>\n<ul>\n  <li>+ to-inf = future duty: <em>Remember to lock</em> the door.</li>\n  <li>+ gerund = past memory: I <em>remember locking</em> it.</li>\n</ul>\n<h4>Forget</h4>\n<ul>\n  <li>+ to-inf = not do: She <em>forgot to submit</em> her assignment.</li>\n  <li>+ gerund = past memory: I'll never <em>forget visiting</em> the Basilica.</li>\n</ul>\n<h4>Stop</h4>\n<ul>\n  <li>+ to-inf = stop in order to: He <em>stopped to buy</em> water. (purpose)</li>\n  <li>+ gerund = stop doing: She <em>stopped talking</em> when teacher entered.</li>\n</ul>\n<h4>Try</h4>\n<ul>\n  <li>+ to-inf = attempt: I <em>tried to open</em> the door but failed.</li>\n  <li>+ gerund = experiment: <em>Try adding</em> more salt \u2014 it might taste better.</li>\n</ul>\n<h3>4. Verb + object + to-infinitive</h3>\n<p><em>want, ask, tell, advise, remind, force, allow, encourage, expect, persuade, help</em></p>\n<ul><li>The teacher <em>told the students to revise</em>. / She <em>encouraged her friend to apply</em>.</li></ul>",
        examples: "<p><strong>To-infinitive:</strong><br>\nShe <em>decided to apply</em> for a scholarship abroad.<br>\nHe <em>managed to pass</em> all his exams despite the difficulties.<br>\nThey <em>refused to accept</em> the unfair conditions.</p>\n<p><strong>Gerund:</strong><br>\nI <em>enjoy writing</em> stories in English.<br>\nYou should <em>avoid making</em> the same mistakes repeatedly.<br>\nHe <em>admitted copying</em> from his classmate.</p>\n<p><strong>Remember:</strong><br>\nPlease <em>remember to bring</em> your exercise book tomorrow. (future duty)<br>\nI clearly <em>remember writing</em> my name on the paper. (past action)</p>\n<p><strong>Stop:</strong><br>\nHe <em>stopped to buy</em> a newspaper on his way home. (in order to buy)<br>\nShe <em>stopped worrying</em> once she had done her best.</p>\n<p><strong>Verb + object + to-inf:</strong><br>\nThe coach <em>encouraged the players to believe</em> in themselves.<br>\nMy parents <em>want me to become</em> a doctor.</p>",
    },
    {
        title: "Leçon 6 (Unité 4) : Writing skills – A for and against essay",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 16,
        duration: 55,
        isPremium: false,
        summary: "Learn to write a balanced for and against essay using formal language, clear structure, strong arguments, and effective linking devices.",
        keyPoints: "A for-and-against essay presents both sides of a topic objectively\nIntroduction: state the issue clearly; do NOT give your opinion yet\nBody 1: arguments FOR + supporting examples and details\nBody 2: arguments AGAINST + supporting examples and details\nConclusion: balanced summary + your overall view or recommendation\nFormal, impersonal tone: avoid \"I think\" in the body; use impersonal structures\nNo contractions; use formal vocabulary and academic linking words\nLinking words: Furthermore / Moreover / However / On the other hand / Consequently",
        content: "<h2>How to Write a For and Against Essay</h2>\n<p>A <strong>for and against essay</strong> presents <strong>both sides</strong> of a topic before reaching a balanced conclusion. It is objective and impersonal.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Formal, impersonal tone (avoid \"I think\" in the main body)</li>\n  <li>Arguments on BOTH sides</li>\n  <li>Topic sentences and linking devices</li>\n  <li>No contractions; academic vocabulary</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Introduction:</strong> State the topic clearly. Do NOT give your opinion yet.<br>\n<strong>Body 1 \u2014 Arguments FOR:</strong> 2\u20133 arguments with details and examples.<br>\n<strong>Body 2 \u2014 Arguments AGAINST:</strong> 2\u20133 counter-arguments with details.<br>\n<strong>Conclusion:</strong> Summarise both sides + balanced view or recommendation.</p>\n<h3>3. Linking Devices</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Adding (for)</td><td>Furthermore, / Moreover, / In addition, / Not only that\u2026</td></tr>\n  <tr><td>Contrasting (against)</td><td>However, / On the other hand, / Nevertheless, / Despite this,</td></tr>\n  <tr><td>Examples</td><td>For example, / For instance, / To illustrate,</td></tr>\n  <tr><td>Concluding</td><td>On the whole, / All things considered, / In conclusion, / To sum up,</td></tr>\n  <tr><td>Cause and effect</td><td>As a result, / Therefore, / Consequently,</td></tr>\n</table>",
        examples: "<p><strong>Topic: Should mobile phones be banned in schools?</strong></p>\n<p><strong>Introduction:</strong><br>\nThe question of whether mobile phones should be permitted in schools has sparked considerable debate in recent years. While some argue that they offer educational benefits, others believe they are a major distraction. Both sides deserve careful consideration.</p>\n<p><strong>Body 1 (FOR \u2014 allowing phones):</strong><br>\nOn the one hand, mobile phones can be valuable educational tools. They give students instant access to information, dictionaries, and educational apps. Furthermore, they allow students to contact parents in emergencies. For instance, in schools that introduced technology programmes, academic performance reportedly improved.</p>\n<p><strong>Body 2 (AGAINST):</strong><br>\nOn the other hand, mobile phones seriously disrupt learning. Students who use phones during lessons miss important information. Moreover, social media becomes addictive, reducing concentration. Cyberbullying is another concern linked to unrestricted phone use among young people.</p>\n<p><strong>Conclusion:</strong><br>\nOn the whole, while mobile phones have educational benefits, their potential to distract outweighs these advantages without rules. The most sensible approach would be limited, supervised use for educational purposes only, with clear rules and consequences.</p>",
    },
    // ── Unité 5 ────────────────────────────────────────────────────────────────
    {
        title: "Leçon 7 (Unité 5) : Language function – Expressing conditions & Making comparisons",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 17,
        duration: 55,
        isPremium: false,
        summary: "Master the four types of conditional sentences (0, 1, 2, 3) and advanced comparison structures including double comparatives and gradual change.",
        keyPoints: "Type 0: present simple + present simple \u2192 general truths\nType 1: if + present simple, will + infinitive \u2192 real/possible future condition\nType 2: if + past simple, would + infinitive \u2192 hypothetical present/future\nType 3: if + past perfect, would have + past participle \u2192 unreal past (regret)\nUse \"were\" (not \"was\") for all persons in Type 2 formal English\nUnless = if not / Provided that / As long as = conditional expressions\nDouble comparative: \"the + comparative, the + comparative\"\nProgressive change: more and more + adjective / comparative + and + comparative",
        content: "<h2>Part A: Conditional Sentences</h2>\n<h3>Type 0 \u2014 General truths</h3>\n<p>Both clauses: <strong>present simple</strong></p>\n<ul><li>If you heat water to 100\u00B0C, it <em>boils</em>.</li></ul>\n<h3>Type 1 \u2014 Real/possible (future)</h3>\n<p>If + <strong>present simple</strong> \u2192 <strong>will + infinitive</strong></p>\n<ul><li>If she <em>studies</em> hard, she <em>will pass</em> the exam.</li></ul>\n<h3>Type 2 \u2014 Hypothetical (present/future)</h3>\n<p>If + <strong>past simple</strong> \u2192 <strong>would + infinitive</strong></p>\n<ul>\n  <li>If I <em>had</em> more time, I <em>would travel</em> the world.</li>\n  <li>Note: \"were\" for all persons in formal English: If I <em>were</em> you, I would accept.</li>\n</ul>\n<h3>Type 3 \u2014 Unreal past (regret)</h3>\n<p>If + <strong>past perfect</strong> \u2192 <strong>would have + past participle</strong></p>\n<ul><li>If he <em>had trained</em> harder, he <em>would have won</em> the race.</li></ul>\n<h3>Other conditional words</h3>\n<ul>\n  <li><em>Unless</em> = if not: Unless you study, you will fail.</li>\n  <li><em>Provided that / As long as</em>: Provided that you pay on time, you can borrow the money.</li>\n</ul>\n<h2>Part B: Advanced Comparisons</h2>\n<h3>Double Comparatives</h3>\n<p>Structure: <em>the + comparative, the + comparative</em></p>\n<ul><li><em>The more you read, the better</em> your English becomes.</li></ul>\n<h3>Progressive change</h3>\n<ul><li>The city is becoming <em>more and more crowded</em>. / His results are getting <em>better and better</em>.</li></ul>",
        examples: "<p><strong>Type 0:</strong> If you mix red and blue paint, you <em>get</em> purple.</p>\n<p><strong>Type 1:</strong> If you <em>revise</em> all your lessons tonight, you <em>will do</em> well tomorrow.</p>\n<p><strong>Type 2:</strong> If I <em>were</em> the head of state, I <em>would invest</em> more in education.</p>\n<p><strong>Type 3:</strong> If she <em>had applied</em> earlier, she <em>would have received</em> the funding.</p>\n<p><strong>Unless:</strong> You will not improve unless you practise speaking every day.</p>\n<p><strong>Double comparative:</strong> The more students read in English, the more confident they become.</p>\n<p><strong>Progressive:</strong> As the exam approaches, students are becoming more and more nervous.</p>",
    },
    {
        title: "Leçon 8 (Unité 5) : Language corner – Relative clauses & Impersonal passive forms",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 18,
        duration: 55,
        isPremium: false,
        summary: "Master defining and non-defining relative clauses, relative pronouns (who, which, that, whose, where), and impersonal passive structures for formal writing.",
        keyPoints: "Defining relative clause: essential info, no commas, \"that\" is possible\nNon-defining relative clause: extra info, USE commas, \"that\" is NOT used\n\"Who/whom\" = people / \"which\" = things / \"that\" = people or things (defining only)\n\"Whose\" = possession / \"where\" = place / \"when\" = time\nImpersonal passive structure 1: It + is/was + past participle + that-clause\nImpersonal passive structure 2: Subject + is/was + past participle + to-infinitive\nCommon verbs: said, believed, thought, reported, claimed, known, considered, expected\nUse impersonal passive to give facts without naming the source (formal style)",
        content: "<h2>Part A: Relative Clauses</h2>\n<h3>1. Defining Relative Clauses</h3>\n<p>Give <strong>essential</strong> information. No commas. \"That\" is possible.</p>\n<ul>\n  <li>The student <em>who won the prize</em> is from our school.</li>\n  <li>This is the book <em>that changed my life</em>.</li>\n  <li>The house <em>where she was born</em> is now a museum.</li>\n</ul>\n<h3>2. Non-Defining Relative Clauses</h3>\n<p>Give <strong>extra</strong> information. USE commas. \"That\" is NOT used.</p>\n<ul>\n  <li>My teacher, <em>who has 20 years of experience</em>, is retiring.</li>\n  <li>The Eiffel Tower, <em>which is in Paris</em>, attracts millions of tourists.</li>\n</ul>\n<h3>3. Relative Pronouns</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Pronoun</th><th>Refers to</th><th>Use</th></tr>\n  <tr><td>who/whom</td><td>people</td><td>who = subject; whom = object (formal)</td></tr>\n  <tr><td>which</td><td>things/animals</td><td>defining and non-defining</td></tr>\n  <tr><td>that</td><td>people/things</td><td>defining clauses only</td></tr>\n  <tr><td>whose</td><td>people/things</td><td>possession</td></tr>\n  <tr><td>where</td><td>places</td><td>replaces \"in which\"</td></tr>\n  <tr><td>when</td><td>time</td><td>replaces \"at which\"</td></tr>\n</table>\n<h2>Part B: Impersonal Passive Forms</h2>\n<h3>Structure 1: It + passive + that-clause</h3>\n<p><em>It is said / believed / thought / reported / claimed that\u2026</em></p>\n<ul><li><em>It is believed that</em> the ruins date back over 2,000 years.</li></ul>\n<h3>Structure 2: Subject + passive + to-infinitive</h3>\n<ul>\n  <li>The ruins <em>are believed to date</em> back over 2,000 years.</li>\n  <li>The suspect <em>is said to have fled</em> the country.</li>\n</ul>",
        examples: "<p><strong>Defining:</strong><br>\nThe candidate <em>who scores highest</em> will be awarded a full scholarship.<br>\nThis is the document <em>that was submitted</em> to the ministry last year.</p>\n<p><strong>Non-defining:</strong><br>\nProfessor Adjoumani, <em>who has published over 40 papers</em>, will chair the conference.<br>\nThe new school library, <em>which was funded by an international organisation</em>, opens next month.</p>\n<p><strong>\"Whose\":</strong><br>\nThe researcher <em>whose study revealed</em> the cure has been nominated for an international prize.</p>\n<p><strong>Impersonal passive \u2014 Structure 1:</strong><br>\n<em>It is widely believed that</em> regular exercise reduces the risk of chronic disease.<br>\n<em>It has been confirmed that</em> the results will be published next week.</p>\n<p><strong>Impersonal passive \u2014 Structure 2:</strong><br>\nThe economy <em>is reported to be growing</em> at 6% per year.<br>\nThe accused <em>is said to have escaped</em> through a back door.</p>",
    },
    {
        title: "Leçon 9 (Unité 5) : Writing skills – A presentation",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 19,
        duration: 50,
        isPremium: false,
        summary: "Learn how to structure and write an effective presentation: engaging opening, signposting language, clear body paragraphs, and a strong conclusion.",
        keyPoints: "A presentation is addressed directly to an audience (use \"you\", \"we\", \"let us\")\nOpening: greet audience, introduce topic, outline structure, engage with a hook\nBody: 2-4 clear points supported by examples, statistics, or illustrations\nUse signposting language to guide the audience through each section\nConclusion: signal end, recap key points, end with call to action or memorable line\nAlways thank the audience and invite questions at the end\nTone: formal or semi-formal depending on context; avoid slang\nRhetorical questions engage the audience: \"Have you ever wondered why...?\"",
        content: "<h2>How to Write and Deliver a Presentation</h2>\n<p>A <strong>presentation</strong> is a formal speech delivered to an audience on a specific topic.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Addressed directly to the audience (use \"you\", \"we\", \"let us\")</li>\n  <li>Clear structure: introduction, body, conclusion</li>\n  <li>Engaging opening; rhetorical questions; statistics</li>\n  <li>Short, clear sentences</li>\n  <li>Strong, memorable conclusion</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Opening:</strong> Greet audience \u2192 introduce yourself \u2192 state topic \u2192 outline structure \u2192 hook<br>\n<strong>Body:</strong> 2\u20134 clear points + signposting + examples/stats<br>\n<strong>Conclusion:</strong> Signal end \u2192 recap \u2192 call to action \u2192 thank audience \u2192 invite questions</p>\n<h3>3. Signposting Language</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Introducing topic</td><td>Today I would like to discuss\u2026 / The purpose of my presentation is to\u2026</td></tr>\n  <tr><td>Moving on</td><td>Let us now turn to\u2026 / Moving on to\u2026 / My next point is\u2026</td></tr>\n  <tr><td>Giving examples</td><td>For example, / To illustrate, / A good example of this is\u2026</td></tr>\n  <tr><td>Concluding</td><td>In conclusion, / To sum up, / I would like to end by\u2026</td></tr>\n</table>",
        examples: "<p><strong>Opening:</strong><br>\nGood morning, ladies and gentlemen. My name is S\u00E9bastien Kouam\u00E9. Today, I would like to talk to you about the impact of social media on students' academic performance.</p>\n<p>Let me begin with a striking fact: the average teenager spends over four hours per day on social media. Have you ever wondered what this means for their studies?</p>\n<p>I will cover three points: first, the educational benefits; second, the negative effects on concentration; and finally, practical recommendations.</p>\n<p><strong>Signposting (body):</strong><br>\nLet us now turn to my first point: the potential benefits. To illustrate, platforms like YouTube allow students to access tutorials at any time...</p>\n<p>Moving on to my second point \u2014 the negative effects. Research shows students who spend more than three hours daily on social media score lower in examinations...</p>\n<p><strong>Conclusion:</strong><br>\nIn conclusion, social media is a double-edged sword. I would strongly encourage every student to set clear boundaries for their screen time. Thank you very much for your attention. I am happy to take any questions.</p>",
    },
    // ── Unité 6 ────────────────────────────────────────────────────────────────
    {
        title: "Le\u00E7on 1 (Unit\u00E9 6) : Language function \u2013 Emphasizing with \"not only ... but also\"",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 20,
        duration: 50,
        isPremium: false,
        summary: "Master the emphatic structure \"not only ... but also\", its inverted form, and related structures: both/and, neither/nor, cleft sentences.",
        keyPoints: "\"Not only ... but also\" emphasizes that two things are true\nWhen \"not only\" starts the sentence, use inverted word order (auxiliary + subject)\nInverted form: Not only did/is/has/was + subject + verb\n\"Both ... and\" joins two positive things equally\n\"Neither ... nor\" joins two negative things\n\"Either ... or\" presents a choice between two things\nCleft sentences \"It is/was ... that/who\" emphasize one element of a sentence\nUsed in formal/written English for rhetorical and emphatic effect",
        content: "<h2>Emphasizing with \"Not only \u2026 but also\"</h2>\n<p>The structure <strong>not only \u2026 but also</strong> emphasizes that two things are true, with the second point adding extra weight to the first.</p>\n<h3>1. Basic Structure</h3>\n<p><strong>Not only + [first point] + but also + [second point]</strong></p>\n<ul>\n  <li>She is <em>not only intelligent but also</em> very hardworking.</li>\n  <li>This plan will <em>not only save time but also</em> reduce costs.</li>\n</ul>\n<h3>2. Inverted Word Order (Formal)</h3>\n<p>When <em>not only</em> starts the sentence, subject and auxiliary verb are <strong>inverted</strong>.</p>\n<ul>\n  <li><em>Not only did she pass</em> the exam, but she also achieved the highest score.</li>\n  <li><em>Not only is he</em> a talented musician, but he is also a gifted writer.</li>\n  <li><em>Not only have they completed</em> the project, but they have also exceeded all expectations.</li>\n</ul>\n<h3>3. Related Emphatic Structures</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Structure</th><th>Example</th></tr>\n  <tr><td>Both \u2026 and</td><td>Both the teacher and the students were surprised.</td></tr>\n  <tr><td>Neither \u2026 nor</td><td>Neither the president nor the minister attended.</td></tr>\n  <tr><td>Either \u2026 or</td><td>Either you study now or you will regret it.</td></tr>\n</table>\n<h3>4. Cleft Sentences for Emphasis</h3>\n<p><em>It is/was \u2026 that/who</em> highlights a specific part of a sentence.</p>\n<ul>\n  <li><em>It was the teacher who</em> noticed the error first.</li>\n  <li><em>It is dedication that</em> separates good students from great ones.</li>\n</ul>",
        examples: "<p><strong>Basic (mid-sentence):</strong><br>\nRegular exercise is <em>not only good for the body but also</em> beneficial for mental health.<br>\nThe new library will <em>not only provide books but also</em> offer free internet access to students.</p>\n<p><strong>Emphatic (inverted):</strong><br>\n<em>Not only did the candidate win</em> the election, but she also broke the record for the most votes ever recorded.<br>\n<em>Not only is water essential</em> for survival, but it also regulates body temperature.</p>\n<p><strong>Related structures:</strong><br>\n<em>Both the government and</em> the private sector must invest in education.<br>\n<em>Neither the student nor</em> his parents had been informed of the examination change.<br>\n<em>It is through consistent effort that</em> great results are achieved, not through luck alone.</p>",
    },
    {
        title: "Leçon 1 (Unité 6) : Language corner – Negative adverbs",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 21,
        duration: 50,
        isPremium: false,
        summary: "Learn how negative adverbs (never, rarely, hardly, scarcely, no sooner) trigger subject-auxiliary inversion for emphasis in formal English.",
        keyPoints: "Negative adverbs (never, rarely, hardly, scarcely) cause subject-auxiliary inversion when at sentence start\nInversion structure: Negative adverb + auxiliary verb + subject + main verb\n\"Never had I seen...\" / \"Rarely does she...\" / \"Scarcely had he arrived when...\"\n\"No sooner ... than\" = immediately after (past perfect + than)\n\"Hardly/Scarcely ... when\" = almost immediately (past perfect + when)\n\"Under no circumstances\" / \"On no account\" / \"In no way\" = absolute negative (inversion required)\nInversion is used in formal/written English for dramatic or emphatic effect",
        content: "<h2>Negative Adverbs</h2>\n<p><strong>Negative adverbs</strong> carry a negative meaning. When placed at the <strong>beginning of a sentence</strong>, the subject and auxiliary verb are <strong>inverted</strong>, creating a formal, emphatic effect.</p>\n<h3>1. Common Negative Adverbs and Phrases</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Adverb/Phrase</th><th>Meaning</th></tr>\n  <tr><td>Never</td><td>at no time</td></tr>\n  <tr><td>Rarely / Seldom</td><td>almost never</td></tr>\n  <tr><td>Hardly / Scarcely / Barely</td><td>almost not</td></tr>\n  <tr><td>No sooner \u2026 than</td><td>immediately after</td></tr>\n  <tr><td>Not until / Not till</td><td>only after a specific time</td></tr>\n  <tr><td>Under no circumstances</td><td>absolutely never</td></tr>\n  <tr><td>On no account</td><td>for no reason / absolutely not</td></tr>\n  <tr><td>In no way</td><td>not at all</td></tr>\n</table>\n<h3>2. Inversion Rule</h3>\n<p><strong>Negative adverb + auxiliary + subject + main verb</strong></p>\n<ul>\n  <li>Never had she seen such a beautiful sunset.</li>\n  <li>Rarely does he speak in public.</li>\n  <li>Scarcely had I arrived when it started raining.</li>\n</ul>\n<h3>3. \"No sooner \u2026 than\" and \"Hardly/Scarcely \u2026 when\"</h3>\n<ul>\n  <li><em>No sooner had</em> she left <em>than</em> the phone rang.</li>\n  <li><em>Hardly had</em> he sat down <em>when</em> the alarm went off.</li>\n  <li>Note: use past perfect + when/than.</li>\n</ul>\n<h3>4. Absolute Prohibitions</h3>\n<ul>\n  <li><em>Under no circumstances should</em> you leave without permission.</li>\n  <li><em>On no account must</em> students use phones during the test.</li>\n  <li><em>In no way does</em> this reflect the views of the committee.</li>\n</ul>",
        examples: "<p><strong>Never (inversion):</strong><br>\n<em>Never have I encountered</em> such dedication in a young student.<br>\n<em>Never before had</em> the school produced so many scholarship winners in a single year.</p>\n<p><strong>Rarely / Seldom:</strong><br>\n<em>Rarely does</em> a student of his age demonstrate such maturity and intellectual depth.</p>\n<p><strong>Hardly \u2026 when:</strong><br>\n<em>Hardly had</em> the minister finished his speech <em>when</em> protesters began chanting outside.</p>\n<p><strong>No sooner \u2026 than:</strong><br>\n<em>No sooner had</em> the new policy been announced <em>than</em> criticism began pouring in from all sides.</p>\n<p><strong>Under no circumstances / On no account:</strong><br>\n<em>Under no circumstances should</em> candidates communicate with one another during the examination.<br>\n<em>On no account must</em> you submit work that has not been checked for errors.</p>",
    },
    {
        title: "Leçon 1 (Unité 6) : Writing skills – An argumentative essay",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 22,
        duration: 55,
        isPremium: false,
        summary: "Learn to write a persuasive argumentative essay: clear thesis, logical arguments, counter-argument refutation, and a strong conclusion.",
        keyPoints: "An argumentative essay takes a CLEAR POSITION and defends it throughout\nIntroduction includes a hook, background context, and a clear thesis statement\nBody para 1 & 2: your strongest arguments + evidence and examples\nBody para 3: acknowledge the counter-argument, then refute it confidently\nConclusion: restate thesis in new words + call to action or recommendation\nPersuasive tone: logical, confident, formal; no contractions\nUse: \"This essay argues that...\" / \"Research shows...\" / \"While it may be argued...\"\nDiffers from for-and-against: you take sides; opinion is stated from the start",
        content: "<h2>How to Write an Argumentative Essay</h2>\n<p>An <strong>argumentative essay</strong> takes a clear <strong>position</strong> on an issue and defends it with logical arguments. Unlike a for-and-against essay, it has a <strong>clear, sustained opinion</strong> throughout.</p>\n<h3>1. Key Differences</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>For and Against</th><th>Argumentative</th></tr>\n  <tr><td>Balanced \u2014 both sides equally</td><td>Takes a clear position</td></tr>\n  <tr><td>Opinion only in conclusion</td><td>Position stated from introduction</td></tr>\n  <tr><td>Objective tone</td><td>Persuasive, logical, confident tone</td></tr>\n</table>\n<h3>2. Structure</h3>\n<p><strong>Introduction:</strong> Hook (fact, statistic, or question) + background + thesis: \"This essay argues that\u2026\"</p>\n<p><strong>Body Para 1 \u2014 Strongest argument:</strong> Claim + evidence/examples + link to thesis.</p>\n<p><strong>Body Para 2 \u2014 Second argument:</strong> Additional evidence.</p>\n<p><strong>Body Para 3 \u2014 Counter-argument + refutation:</strong> Acknowledge opposing view, then refute strongly: \"While some argue that\u2026 / Although it is true that\u2026\"</p>\n<p><strong>Conclusion:</strong> Restate thesis in different words + summarise + recommendation or call to action.</p>\n<h3>3. Useful Language</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Stating position</td><td>This essay argues that\u2026 / I strongly believe that\u2026</td></tr>\n  <tr><td>Supporting</td><td>Research shows that\u2026 / Evidence suggests\u2026 / A compelling example is\u2026</td></tr>\n  <tr><td>Counter-argument</td><td>While it may be argued that\u2026 / Admittedly, \u2026 However,\u2026</td></tr>\n  <tr><td>Concluding</td><td>In conclusion, / Therefore, I urge\u2026 / It is clear that\u2026</td></tr>\n</table>",
        examples: "<p><strong>Topic: Education should be free at all levels.</strong></p>\n<p><strong>Introduction:</strong><br>\nOver 258 million children worldwide are out of school. This essay firmly argues that free education at all levels is not only a fundamental human right but also an economic necessity for any developing nation.</p>\n<p><strong>Body paragraph 1:</strong><br>\nFirst and foremost, free education eliminates financial barriers. In C\u00F4te d'Ivoire, many gifted students abandon their studies due to high fees. Research shows that nations with free education produce more graduates, driving economic growth and reducing poverty.</p>\n<p><strong>Counter-argument + refutation:</strong><br>\nAdmittedly, critics argue that free education is an unsustainable burden on public finances. While this is valid, it ignores the long-term economic returns of an educated workforce. The initial cost is vastly outweighed by long-term benefits.</p>\n<p><strong>Conclusion:</strong><br>\nIn conclusion, free education is not a luxury \u2014 it is a foundation for social justice. Governments must recognise education as their most powerful investment and work to eliminate all financial barriers to learning.</p>",
    },
    // ── Unité 7 ────────────────────────────────────────────────────────────────
    {
        title: "Leçon 2 (Unité 7) : Language function – Giving orders and requests",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 23,
        duration: 50,
        isPremium: false,
        summary: "Master the full spectrum of giving orders and requests: direct imperatives, polite modal forms, and reported orders with the correct infinitive structure.",
        keyPoints: "The imperative (base verb) gives direct orders: \"Sit down / Don't touch that\"\n\"Do + imperative\" adds emphasis or politeness: \"Do come in!\"\nPolite requests use modals: Can you / Could you / Would you / Will you\n\"Would you mind + -ing?\" is very polite; answer \"No\" = you agree\nReported orders: tell/order/command + object + to-infinitive\nReported requests: ask/beg/request + object + to-infinitive\nReported negative: warn/advise/forbid + object + NOT to-infinitive\n\"Would you mind + -ing?\" expects \"No, not at all\" (agreement) or \"Yes, I would\" (refusal)",
        content: "<h2>Giving Orders and Requests</h2>\n<p>Orders and requests range from direct commands to polite, indirect forms. Choosing the right form depends on context and formality.</p>\n<h3>1. Direct Orders (Imperative)</h3>\n<ul>\n  <li>Positive: <em>Sit down. / Open your books. / Listen carefully.</em></li>\n  <li>Negative: <em>Don't touch that. / Do not leave without permission.</em></li>\n  <li>With \"do\" for emphasis: <em>Do come in! / Do be quiet!</em></li>\n</ul>\n<h3>2. Polite Requests</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Structure</th><th>Formality</th><th>Example</th></tr>\n  <tr><td>Can you\u2026?</td><td>Informal</td><td>Can you close the window?</td></tr>\n  <tr><td>Could you\u2026?</td><td>Neutral/polite</td><td>Could you pass me the file?</td></tr>\n  <tr><td>Would you\u2026?</td><td>Formal and polite</td><td>Would you mind signing this?</td></tr>\n  <tr><td>Would you mind + -ing?</td><td>Very polite</td><td>Would you mind waiting a moment?</td></tr>\n  <tr><td>I would be grateful if\u2026</td><td>Very formal/written</td><td>I would be grateful if you could send the report.</td></tr>\n</table>\n<h3>3. Reported Orders and Requests</h3>\n<ul>\n  <li><strong>Tell, order, command + object + to-inf:</strong> The teacher <em>told the students to sit</em> down.</li>\n  <li><strong>Ask, request, beg + object + to-inf:</strong> She <em>asked him to wait</em> outside.</li>\n  <li><strong>Warn, advise + object + not to-inf:</strong> The doctor <em>warned him not to smoke</em>.</li>\n  <li><strong>Forbid + object + to-inf:</strong> The director <em>forbade anyone to enter</em>.</li>\n</ul>\n<h3>4. Permission and Prohibition</h3>\n<ul>\n  <li>Permission: <em>You may / can / are allowed to + base verb</em></li>\n  <li>Prohibition: <em>You must not / cannot / are not allowed to + base verb</em></li>\n</ul>",
        examples: "<p><strong>Direct orders:</strong><br>\n<em>Open</em> your exam booklets when told to do so. <em>Do not</em> write anything until the invigilator signals.</p>\n<p><strong>Polite requests (escalating formality):</strong><br>\n\"<em>Can you</em> lend me your pen?\" (informal)<br>\n\"<em>Could you please</em> check this paragraph?\" (polite)<br>\n\"<em>Would you mind</em> moving your bag?\" (very polite)<br>\n\"<em>I would be grateful if you could</em> submit your report by Friday.\" (formal)</p>\n<p><strong>Reported orders:</strong><br>\nThe examiner <em>told all candidates to switch off</em> their phones.<br>\nShe <em>asked her teacher not to mark</em> her late.<br>\nParents <em>were reminded to collect</em> their children by 5 p.m.</p>\n<p><strong>\"Would you mind\":</strong><br>\n\"Would you mind closing the door?\" \u2014 \"No, not at all.\" \u2705 (agreement)<br>\n\"Would you mind helping me?\" \u2014 \"Yes, I would, I am rather busy.\" \u274C (refusal)</p>",
    },
    {
        title: "Leçon 2 (Unité 7) : Language corner – Prepositions & Reported speech",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 24,
        duration: 55,
        isPremium: false,
        summary: "Master prepositions of time and place, common fixed expressions, and the full rules of reported speech including tense backshift and question reporting.",
        keyPoints: "Prepositions of time: at (specific times) / on (days, dates) / in (months, years, seasons)\n\"For\" = duration / \"since\" = starting point to now / \"by\" = deadline\nPrepositions of place: at (a point) / in (inside) / on (surface)\nFixed expressions: on time, in time, on purpose, by mistake, in spite of\nReported speech: tenses shift back one step (present \u2192 past / past \u2192 past perfect)\nTime expressions change: now \u2192 then / today \u2192 that day / tomorrow \u2192 the next day\nPronouns change to match the new speaker's perspective\nReported questions: use if/whether (yes/no) or wh-word + normal word order (no inversion)",
        content: "<h2>Part A: Prepositions</h2>\n<h3>1. Prepositions of Time</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Preposition</th><th>Use</th><th>Example</th></tr>\n  <tr><td>at</td><td>specific times; holidays</td><td>at 8 a.m. / at Christmas</td></tr>\n  <tr><td>on</td><td>days and dates</td><td>on Monday / on 15th April</td></tr>\n  <tr><td>in</td><td>months, years, seasons</td><td>in April / in 2026 / in winter</td></tr>\n  <tr><td>for</td><td>duration</td><td>for three hours</td></tr>\n  <tr><td>since</td><td>starting point up to now</td><td>since 2020</td></tr>\n  <tr><td>by</td><td>deadline (not later than)</td><td>by Friday / by 6 p.m.</td></tr>\n  <tr><td>during</td><td>within a period</td><td>during the holidays</td></tr>\n  <tr><td>until/till</td><td>up to a point in time</td><td>until midnight</td></tr>\n</table>\n<h3>2. Prepositions of Place</h3>\n<ul>\n  <li><strong>at</strong> = a point: at the door / at school</li>\n  <li><strong>in</strong> = inside: in the room / in Abidjan</li>\n  <li><strong>on</strong> = on a surface: on the table / on the wall</li>\n  <li><strong>to</strong> = movement towards: go to school</li>\n</ul>\n<h3>3. Fixed Prepositional Phrases</h3>\n<p><em>by mistake, on purpose, in a hurry, on time, in time, in spite of, on behalf of, according to, instead of</em></p>\n<h2>Part B: Reported Speech</h2>\n<h3>Tense Backshift</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Direct speech</th><th>Reported speech</th></tr>\n  <tr><td>\"I study\"</td><td>said he studied</td></tr>\n  <tr><td>\"I am working\"</td><td>said she was working</td></tr>\n  <tr><td>\"I have finished\"</td><td>said he had finished</td></tr>\n  <tr><td>\"I went\"</td><td>said she had gone</td></tr>\n  <tr><td>\"I will help\"</td><td>said he would help</td></tr>\n  <tr><td>\"I can come\"</td><td>said she could come</td></tr>\n  <tr><td>\"I must leave\"</td><td>said he had to leave</td></tr>\n</table>\n<h3>Time/Place Changes</h3>\n<ul>\n  <li>now \u2192 then / today \u2192 that day / tomorrow \u2192 the next day / here \u2192 there</li>\n</ul>\n<h3>Reporting Questions</h3>\n<ul>\n  <li>Yes/No: <em>ask + if/whether</em> \u2192 She asked <em>if I was ready</em>.</li>\n  <li>Wh-: <em>ask + wh-word + subject + verb</em> \u2192 He asked <em>where I lived</em>.</li>\n</ul>",
        examples: "<p><strong>Prepositions of time:</strong><br>\nThe ceremony begins <em>at</em> 10 a.m. <em>on</em> Saturday, <em>in</em> May.<br>\nShe has been studying <em>since</em> 7 a.m. and will continue <em>until</em> midday.<br>\nPlease submit your assignment <em>by</em> Friday at the latest.</p>\n<p><strong>Fixed phrases:</strong><br>\nHe arrived <em>on time</em>. <em>In spite of</em> the difficulty, she passed.</p>\n<p><strong>Reported speech \u2014 statements:</strong><br>\nDirect: \"I am preparing for the Baccalaureate,\" she said.<br>\nReported: She said she <em>was preparing</em> for the Baccalaureate.</p>\n<p>Direct: \"I have already submitted my project,\" he told the teacher.<br>\nReported: He told the teacher he <em>had already submitted</em> his project.</p>\n<p><strong>Reported questions:</strong><br>\nDirect: \"Do you understand the lesson?\"<br>\nReported: The teacher asked <em>whether I understood</em> the lesson.</p>\n<p>Direct: \"Where did you go after school?\"<br>\nReported: She asked <em>where I had gone</em> after school.</p>",
    },
    {
        title: "Leçon 2 (Unité 7) : Writing skills – An opinion essay",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 25,
        duration: 55,
        isPremium: false,
        summary: "Learn to write a well-structured opinion essay: stating your position clearly, developing reasons with evidence, acknowledging other views, and concluding persuasively.",
        keyPoints: "An opinion essay states the writer's clear personal view from the introduction\nIntroduction: hook + background + clear statement of opinion (\"In my view...\")\nBody paragraphs: each focuses on ONE reason/argument + evidence + example\nOptional concession paragraph: briefly acknowledge opposite view, then return to your position\nConclusion: restate opinion in new words + leave a strong closing thought\nFormal and persuasive tone; no contractions; structured topic sentences\nUse emphatic language: clearly, undoubtedly, there is no doubt that\nUse hedging where appropriate: it seems, may, appear, tend to",
        content: "<h2>How to Write an Opinion Essay</h2>\n<p>An <strong>opinion essay</strong> presents the writer's personal viewpoint on a controversial topic. The goal is to persuade the reader using well-structured arguments and formal language.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Writer's opinion clearly stated from the beginning</li>\n  <li>Formal, persuasive tone throughout</li>\n  <li>Uses hedging (may, might, seems) and emphatic language (clearly, undoubtedly)</li>\n  <li>No contractions; structured paragraphs with topic sentences</li>\n  <li>Ends with a strong conclusion reaffirming the position</li>\n</ul>\n<h3>2. Structure</h3>\n<p><strong>Introduction:</strong> Hook \u2192 state your opinion: <em>\"In my view\u2026\" / \"I firmly believe that\u2026\"</em></p>\n<p><strong>Body Para 1:</strong> First reason + explanation + example.</p>\n<p><strong>Body Para 2:</strong> Second reason + development.</p>\n<p><strong>Body Para 3 (Optional \u2014 Concession):</strong> <em>\"Admittedly, some argue that\u2026\"</em> \u2014 then return to your position.</p>\n<p><strong>Conclusion:</strong> Restate opinion in new words + summarise + thought-provoking final statement.</p>\n<h3>3. Useful Language</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Stating opinion</td><td>In my view, / I am convinced that\u2026 / Personally, I believe\u2026</td></tr>\n  <tr><td>Adding reasons</td><td>First of all, / Furthermore, / What is more,</td></tr>\n  <tr><td>Concession</td><td>Admittedly, / It is true that\u2026 / Although\u2026</td></tr>\n  <tr><td>Emphasising</td><td>Clearly, / Undoubtedly, / There is no doubt that\u2026</td></tr>\n  <tr><td>Concluding</td><td>In conclusion, / Ultimately, / All in all,</td></tr>\n</table>",
        examples: "<p><strong>Topic: Young people today are too dependent on technology.</strong></p>\n<p><strong>Introduction:</strong><br>\nHave you ever seen a teenager look up from their phone long enough to have a meaningful conversation? In my view, the over-reliance of young people on technology is a serious problem that undermines their social skills, creativity, and independence.</p>\n<p><strong>Body para 1:</strong><br>\nFirst of all, excessive technology use significantly damages young people's ability to communicate face to face. Studies show that those spending more than four hours a day on screens struggle with eye contact and empathy.</p>\n<p><strong>Concession:</strong><br>\nAdmittedly, technology offers remarkable learning opportunities. However, access to information is only beneficial when young people develop the discipline to use it wisely \u2014 a skill clearly lacking among many today.</p>\n<p><strong>Conclusion:</strong><br>\nIn conclusion, while technology is a powerful tool, it must not become a crutch. I firmly believe young people need digital discipline from an early age. Ultimately, the measure of a generation is not how many apps it uses, but how well it thinks, creates, and connects.</p>",
    },
    // ── Unité 8 ────────────────────────────────────────────────────────────────
    {
        title: "Leçon 3 (Unité 8) : Language function – Verb patterns",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 26,
        duration: 55,
        isPremium: false,
        summary: "Master key verb patterns in English: verb + that-clause, verb + wh-clause, verb + to-infinitive, verb + gerund, and impersonal constructions.",
        keyPoints: "Verb + that-clause: say/think/believe/know/feel/admit/claim + (that) + subject + verb\n\"That\" is optional in informal English but required in formal writing\nVerb + wh-clause (embedded questions): use statement word order (NOT question order)\n\"I don't know where she is\" NOT \"I don't know where is she\"\nVerb + to-infinitive: decide, seem, appear, hope, manage, refuse, expect\nVerb + gerund (-ing): enjoy, avoid, admit, deny, finish, keep, risk, suggest\nVerb + object + complement: consider (him talented) / call (it a success) / make (them work)\nImpersonal constructions: \"It seems that...\" / \"It is important that...\" / \"It was reported that...\"",
        content: "<h2>Referring to What Follows a Verb Using Verb Patterns</h2>\n<p>In English, many verbs are followed by a specific complement \u2014 a <strong>that-clause</strong>, a <strong>wh-clause</strong>, a <strong>to-infinitive</strong>, or a <strong>gerund</strong>.</p>\n<h3>1. Verb + That-Clause</h3>\n<p>Common verbs: <em>say, think, believe, know, feel, hope, expect, suggest, admit, claim, confirm, deny, realise, understand, agree, decide</em></p>\n<ul>\n  <li>She <em>believes (that) education</em> is the key to success.</li>\n  <li>He <em>admitted (that) he had made</em> a mistake.</li>\n  <li>Scientists <em>confirm that climate change</em> is accelerating.</li>\n</ul>\n<h3>2. Verb + Wh-Clause (Embedded Questions)</h3>\n<p>Use <em>wh-word + subject + verb</em> (NOT question word order).</p>\n<p>Common verbs: <em>know, wonder, ask, tell, show, explain, decide, understand, forget, remember</em></p>\n<ul>\n  <li>I don't know <em>where she has gone</em>. (NOT: where has she gone)</li>\n  <li>Could you explain <em>how this works</em>?</li>\n</ul>\n<h3>3. Verb + to-Infinitive</h3>\n<ul>\n  <li>She <em>decided to apply</em> for the position.</li>\n  <li>They <em>appear to have completed</em> the project early.</li>\n</ul>\n<h3>4. Verb + -ing (Gerund)</h3>\n<ul>\n  <li>She <em>enjoys writing</em> poetry. / He <em>avoids making</em> eye contact.</li>\n</ul>\n<h3>5. Verb + Object + Complement</h3>\n<ul>\n  <li>Object + adjective: They <em>consider him talented</em>.</li>\n  <li>Object + noun: She <em>called it a masterpiece</em>.</li>\n  <li>Object + bare infinitive: She <em>made the students rewrite</em> the essay.</li>\n</ul>\n<h3>6. Impersonal Constructions</h3>\n<ul>\n  <li><em>It seems that</em> the situation is improving.</li>\n  <li><em>It is important that</em> students revise regularly.</li>\n  <li><em>It was reported that</em> the results were outstanding.</li>\n</ul>",
        examples: "<p><strong>Verb + that-clause:</strong><br>\nThe committee <em>agreed that</em> the new curriculum was beneficial to all students.<br>\nResearch <em>confirms that</em> reading regularly improves vocabulary and comprehension.</p>\n<p><strong>Verb + wh-clause:</strong><br>\nMany students do not <em>understand how</em> the grading system works.<br>\nCould you <em>explain what</em> is expected of us in the final examination?</p>\n<p><strong>Verb + object + complement:</strong><br>\nThe judges <em>declared her the winner</em> of the national essay competition.<br>\nThe school director <em>made all students attend</em> the compulsory orientation session.</p>\n<p><strong>Impersonal constructions:</strong><br>\n<em>It is widely believed that</em> a strong foundation in literacy determines long-term academic success.<br>\n<em>It appears that</em> the number of students choosing science subjects is steadily increasing.</p>",
    },
    {
        title: "Leçon 3 (Unité 8) : Language corner – Question types in English",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 27,
        duration: 50,
        isPremium: false,
        summary: "Master all English question types: yes/no, wh-questions, tag questions, indirect questions, and rhetorical questions — with correct word order for each.",
        keyPoints: "Yes/No questions: invert subject and auxiliary (be, have, do, modal)\nUse do/does/did when there is no auxiliary verb in the statement\nWh-questions: wh-word + auxiliary + subject + verb\nException: when wh-word IS the subject, no inversion (\"Who called you?\")\nTag questions: positive statement \u2192 negative tag; negative statement \u2192 positive tag\nIrregular tags: \"I am right, aren't I?\" / \"Let's go, shall we?\"\nIndirect questions: question word + normal word order (NO inversion, NO do/does/did)\nRhetorical questions are not genuine \u2014 they make a point or persuade",
        content: "<h2>Question Types in English</h2>\n<h3>1. Yes/No Questions</h3>\n<p>Formed by inverting subject and auxiliary verb.</p>\n<ul>\n  <li><em>Is</em> she a student? / <em>Have</em> you seen the film? / <em>Does</em> he study here?</li>\n  <li>If no auxiliary verb exists, use <strong>do/does/did</strong>: <em>Does</em> she speak English?</li>\n</ul>\n<h3>2. Wh- Questions</h3>\n<p>Begin with: <strong>who, what, when, where, why, which, how, how long, how many, how much</strong></p>\n<p>Structure: <strong>Wh-word + auxiliary + subject + main verb</strong></p>\n<ul>\n  <li><em>What do</em> you study? / <em>Where does</em> she live?</li>\n  <li>When wh-word IS the subject \u2014 no inversion: <em>Who called you? / What happened?</em></li>\n</ul>\n<h3>3. Tag Questions</h3>\n<ul>\n  <li>Positive statement \u2192 Negative tag: She is a doctor, <em>isn't she</em>?</li>\n  <li>Negative statement \u2192 Positive tag: He doesn't like it, <em>does he</em>?</li>\n  <li>Irregular: I am right, <em>aren't I</em>? / Let's go, <em>shall we</em>? / Don't be late, <em>will you</em>?</li>\n</ul>\n<h3>4. Indirect / Embedded Questions</h3>\n<p>Used to ask politely. <strong>No inversion \u2014 use normal word order.</strong></p>\n<ul>\n  <li>Direct: Where is the station? \u2192 Indirect: <em>Could you tell me where the station is</em>?</li>\n  <li>Direct: Is she available? \u2192 Indirect: <em>I was wondering if she is available</em>.</li>\n</ul>\n<h3>5. Rhetorical Questions</h3>\n<p>Used for emphasis or persuasion \u2014 the speaker does not expect an answer.</p>\n<ul>\n  <li><em>Is there anyone who does not want a better future?</em></li>\n  <li><em>What is the point of studying if you don't apply what you learn?</em></li>\n</ul>\n<h3>6. Choice Questions (Either/Or)</h3>\n<ul>\n  <li><em>Would you prefer tea or coffee? / Are you going by bus or by taxi?</em></li>\n</ul>",
        examples: "<p><strong>Yes/No questions:</strong><br>\n<em>Has she submitted</em> her application yet? <em>Did you attend</em> the ceremony yesterday?</p>\n<p><strong>Wh-questions:</strong><br>\n<em>What subjects does</em> she study at Terminale?<br>\n<em>Who discovered</em> the problem first? (subject \u2014 no inversion)<br>\n<em>How many students have passed</em> the Baccalaureate this year?</p>\n<p><strong>Tag questions:</strong><br>\nThe exam results were excellent, <em>weren't they</em>?<br>\nShe hasn't revised yet, <em>has she</em>?<br>\nLet's celebrate our success, <em>shall we</em>?</p>\n<p><strong>Indirect questions:</strong><br>\nDirect: \"Where does the headmaster's office?\" \u2192<br>\nIndirect: <em>Could you tell me where the headmaster's office is</em>? (no inversion)<br>\nDirect: \"Is the school open on Saturday?\" \u2192<br>\nIndirect: <em>I would like to know whether the school is open on Saturday</em>.</p>\n<p><strong>Rhetorical question:</strong><br>\n<em>Can we truly claim to be developing</em> if half our children have no access to quality education?</p>",
    },
    {
        title: "Leçon 3 (Unité 8) : Writing skills – A covering letter",
        subjectId: ANGLAIS_SUBJECT_ID,
        series: "ALL",
        order: 28,
        duration: 50,
        isPremium: false,
        summary: "Learn to write a compelling covering letter for a job or scholarship application: formal layout, confident language, tailored motivation, and a professional closing.",
        keyPoints: "A covering letter accompanies a CV when applying for a job, scholarship, or programme\nFormal register: no contractions, no slang; professional and confident tone\nLayout: your address \u2192 date \u2192 recipient address \u2192 subject line \u2192 salutation\nPara 1: state the position you are applying for, where you saw it, and your interest\nPara 2: highlight relevant qualifications, skills, and experience with specific examples\nPara 3: show you know the organisation and explain why you want THIS specific role\nPara 4: request an interview, mention enclosed CV, thank the reader\n\"Yours sincerely\" if you used their name; \"Yours faithfully\" if \"Dear Sir/Madam\"\nTailor each letter to the specific role \u2014 never send a generic letter",
        content: "<h2>How to Write a Covering Letter (Cover Letter)</h2>\n<p>A <strong>covering letter</strong> is a formal letter sent alongside a CV when applying for a job, scholarship, or programme. Its purpose is to introduce yourself, explain your interest and suitability, and persuade the recruiter to read your full application.</p>\n<h3>1. Key Features</h3>\n<ul>\n  <li>Formal register \u2014 no contractions, no slang</li>\n  <li>Confident, professional, and concise (ideally one page)</li>\n  <li>Tailored to the specific role or programme</li>\n  <li>Highlights your most relevant skills and experience</li>\n</ul>\n<h3>2. Structure / Layout</h3>\n<p><strong>Your full name and address</strong> (top right)<br>\n<strong>Date</strong><br>\n<strong>Recipient's name/title and address</strong> (left-aligned)<br>\n<strong>Subject line:</strong> RE: Application for [Position / Scholarship]</p>\n<p><strong>Salutation:</strong> Dear Mr/Mrs/Ms [Surname], \u2014 OR \u2014 Dear Sir/Madam</p>\n<p><strong>Para 1 \u2014 Introduction:</strong> State the position you are applying for, where you saw it, and express genuine interest.</p>\n<p><strong>Para 2 \u2014 Qualifications and skills:</strong> Highlight relevant qualifications and experience. Use specific examples \u2014 connect them to the role.</p>\n<p><strong>Para 3 \u2014 Your motivation:</strong> Show you have researched the organisation. Explain why you want THIS specific role.</p>\n<p><strong>Para 4 \u2014 Closing:</strong> Express eagerness for an interview. Mention your CV is enclosed. Thank the reader.</p>\n<p><strong>Sign-off:</strong> Yours sincerely (if name used) / Yours faithfully (if Dear Sir/Madam)</p>\n<h3>3. Useful Expressions</h3>\n<table border=\"1\" cellpadding=\"6\" style=\"border-collapse:collapse;width:100%\">\n  <tr><th>Function</th><th>Expressions</th></tr>\n  <tr><td>Applying</td><td>I am writing to apply for\u2026 / I wish to apply for the position of\u2026</td></tr>\n  <tr><td>Qualifications</td><td>I hold a Baccalaureate in\u2026 / I have experience in\u2026 / I am proficient in\u2026</td></tr>\n  <tr><td>Motivation</td><td>I am particularly drawn to\u2026 / Your organisation is renowned for\u2026</td></tr>\n  <tr><td>Interview</td><td>I would welcome the opportunity to discuss\u2026 / I am available at your convenience.</td></tr>\n  <tr><td>Closing</td><td>I look forward to hearing from you. / Please find my CV enclosed.</td></tr>\n</table>",
        examples: "<p>Kouassi Ama B\u00E9n\u00E9dicte<br>25, Rue des Jardins, Cocody, Abidjan<br>9th April 2026</p>\n<p>The Scholarship Committee<br>Foundation for African Excellence, Abidjan</p>\n<p><strong>RE: Application for the Excellence Scholarship in Sciences</strong></p>\n<p>Dear Sir/Madam,</p>\n<p>I am writing to apply for the Excellence Scholarship in Sciences, which I came across on your official website. I am deeply inspired by your commitment to developing the next generation of African scientists.</p>\n<p>I am currently a Terminale D student at Lyc\u00E9e Moderne de Bingerville, where I have consistently ranked first in Mathematics, Physics, and Chemistry. Last year, I represented my school in the national science olympiad, where my team placed second. I aspire to study biomedical engineering.</p>\n<p>Your foundation is renowned for the mentorship programmes it offers alongside financial support \u2014 a combination I consider invaluable. I am confident this scholarship will enable me to pursue my studies at the highest level.</p>\n<p>I would welcome the opportunity to discuss my application at your convenience. Please find my academic records enclosed. I thank you sincerely for taking the time to consider my application.</p>\n<p>Yours faithfully,<br><strong>Kouassi Ama B\u00E9n\u00E9dicte</strong></p>",
    },
];
function seedAnglaisLessons() {
    return __awaiter(this, void 0, void 0, function () {
        var existing, existingOrders, _i, anglaisLessons_1, lesson, err_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    _a.trys.push([0, 6, , 7]);
                    return [4 /*yield*/, db_1.db
                            .select({ order: db_1.lessonsTable.order })
                            .from(db_1.lessonsTable)
                            .where((0, drizzle_orm_1.and)((0, drizzle_orm_1.eq)(db_1.lessonsTable.subjectId, ANGLAIS_SUBJECT_ID), (0, drizzle_orm_1.gte)(db_1.lessonsTable.order, SEED_MARKER_ORDER_START)))];
                case 1:
                    existing = _a.sent();
                    if (existing.length >= 24) {
                        logger_1.logger.info("Anglais seed lessons already present — skipping");
                        return [2 /*return*/];
                    }
                    existingOrders = new Set(existing.map(function (r) { return r.order; }));
                    _i = 0, anglaisLessons_1 = anglaisLessons;
                    _a.label = 2;
                case 2:
                    if (!(_i < anglaisLessons_1.length)) return [3 /*break*/, 5];
                    lesson = anglaisLessons_1[_i];
                    if (existingOrders.has(lesson.order))
                        return [3 /*break*/, 4];
                    return [4 /*yield*/, db_1.db.insert(db_1.lessonsTable).values({
                            title: lesson.title,
                            subjectId: lesson.subjectId,
                            series: lesson.series,
                            order: lesson.order,
                            duration: lesson.duration,
                            isPremium: lesson.isPremium,
                            summary: lesson.summary,
                            keyPoints: lesson.keyPoints,
                            content: lesson.content,
                            examples: lesson.examples,
                        })];
                case 3:
                    _a.sent();
                    logger_1.logger.info({ title: lesson.title }, "Seeded Anglais lesson");
                    _a.label = 4;
                case 4:
                    _i++;
                    return [3 /*break*/, 2];
                case 5:
                    logger_1.logger.info("Anglais lessons seed complete");
                    return [3 /*break*/, 7];
                case 6:
                    err_1 = _a.sent();
                    logger_1.logger.error({ err: err_1 }, "Failed to seed Anglais lessons");
                    return [3 /*break*/, 7];
                case 7: return [2 /*return*/];
            }
        });
    });
}
