"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var health_js_1 = require("./health.js");
var auth_js_1 = require("./auth.js");
var replitAuth_js_1 = require("./replitAuth.js");
var users_js_1 = require("./users.js");
var subjects_js_1 = require("./subjects.js");
var lessons_js_1 = require("./lessons.js");
var exercises_js_1 = require("./exercises.js");
var exams_js_1 = require("./exams.js");
var progress_js_1 = require("./progress.js");
var gamification_js_1 = require("./gamification.js");
var reviews_js_1 = require("./reviews.js");
var chat_js_1 = require("./chat.js");
var admin_js_1 = require("./admin.js");
var router = (0, express_1.Router)();
router.use(health_js_1.default);
router.use(replitAuth_js_1.default);
router.use("/auth", auth_js_1.default);
router.use("/users", users_js_1.default);
router.use("/subjects", subjects_js_1.default);
router.use("/lessons", lessons_js_1.default);
router.use("/exercises", exercises_js_1.default);
router.use("/exams", exams_js_1.default);
router.use("/progress", progress_js_1.default);
router.use(gamification_js_1.default);
router.use("/reviews", reviews_js_1.default);
router.use("/chat", chat_js_1.default);
router.use("/admin", admin_js_1.default);
exports.default = router;
